import { Link } from 'wouter';
import { ArrowRight } from 'lucide-react';
import Layout from '@/components/Layout';
import { images } from '@/lib/constants';

function AboutPage() {
  return <Layout><main><section className="page-hero"><div className="container-wide"><div className="eyebrow">About Wizard’s</div><h1>The craft behind<br /><em>the finish.</em></h1><p>Professional mobile detailing built around careful workmanship and the convenience of bringing the service to you.</p></div></section><section className="section"><div className="container-wide about-grid"><div className="about-image" style={{ backgroundImage: `url(${images.work})` }} /><div><div className="eyebrow">Who we are</div><h2>Attention is the point.</h2><p className="body-copy">Wizard’s Auto Detailing serves Montreal and surrounding areas with mobile interior, exterior, polishing, and ceramic coating services. The approach is deliberately practical: inspect the vehicle, respect the setting, and give every surface the attention it deserves.</p><p className="body-copy">No artificial founder story, inflated claims, or invented credentials — just a clean place to understand the work and request an appointment.</p></div></div></section><section className="section section-soft"><div className="container-wide"><div className="section-head"><div><div className="eyebrow">What we believe</div><h2>The details<br />set the tone.</h2></div><p>From the first conversation to the final reflection, the experience should feel clear, careful, and considered.</p></div><div className="beliefs">{[['Attention to detail', 'The small surfaces are part of the result.'], ['Respect for the vehicle', 'Every vehicle gets an inspection before the scope is set.'], ['Professional finish', 'The goal is a composed, clean result — not a rushed pass.'], ['Convenience', 'Mobile service brings the work to a suitable location.']].map(([x, y]) => <div className="belief" key={x}><b>{x}</b><p>{y}</p></div>)}</div></div></section><section className="section"><div className="container-wide split-visual"><div><div className="eyebrow">Mobile service</div><h2>At home.<br />At work.<br /><em>Where it fits.</em></h2><p className="body-copy">Home, workplace, or another suitable location: share where the vehicle will be available and Wizard’s can coordinate from there. Appointments remain subject to location confirmation.</p><Link href="/book" className="button-gold" data-testid="link-about-book">Book with Wizard’s <ArrowRight size={14} /></Link></div><div className="visual-frame" style={{ backgroundImage: `url(${images.exterior})` }} /></div></section><section className="cta-band"><div className="container-wide"><div className="eyebrow">The next detail</div><h2>Bring the vehicle. We’ll bring the care.</h2><Link href="/book" className="button-gold" data-testid="link-about-final-book">Request an appointment <ArrowRight size={14} /></Link></div></section></main></Layout>;
}
export default AboutPage;
