import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import { useCreateBookingRequest, BookingRequestInput } from '@/api-client';
import Layout from '@/components/Layout';
import { Field } from '@/components/ui/form-field';
import { phone, services } from '@/lib/constants';

const initialBooking: BookingRequestInput = { fullName: '', email: '', phone: '', preferredContactMethod: 'phone', vehicleMake: '', vehicleModel: '', vehicleYear: null, vehicleType: 'sedan', vehicleColor: null, vehicleCondition: 'unsure', services: [], serviceNotes: null, serviceAddress: '', city: 'Montreal', postalCode: '', locationType: null, accessNotes: null, preferredDate: '', preferredTime: '', alternativeDate: null, alternativeTime: null, notes: null, consent: false, website: '' };
const bookingSteps = ['Contact', 'Vehicle', 'Service', 'Location', 'Time', 'Confirm'];

function BookPage() {
  const [form, setForm] = useState<BookingRequestInput>(initialBooking);
  const [step, setStep] = useState(0);
  const [errors, setErrors] = useState<string[]>([]);
  const [success, setSuccess] = useState(false);
  const mutation = useCreateBookingRequest();
  const set = (key: keyof BookingRequestInput, value: unknown) => setForm((prev) => ({ ...prev, [key]: value }));
  const validate = () => {
    const e: string[] = [];
    if (step === 0) { if (form.fullName.trim().length < 2) e.push('Please enter your full name.'); if (!/^\S+@\S+\.\S+$/.test(form.email)) e.push('Please enter a valid email.'); if (form.phone.replace(/\D/g, '').length < 7) e.push('Please enter a valid phone number.'); }
    if (step === 1) { if (!form.vehicleMake) e.push('Vehicle make is required.'); if (!form.vehicleModel) e.push('Vehicle model is required.'); }
    if (step === 2 && form.services.length === 0) e.push('Choose at least one service.'); if (step === 3) { if (form.serviceAddress.trim().length < 3) e.push('Service address is required.'); if (form.city.trim().length < 2) e.push('City is required.'); if (form.postalCode.trim().length < 3) e.push('Postal code is required.'); } if (step === 4) { if (!form.preferredDate) e.push('Choose a preferred date.'); if (!form.preferredTime) e.push('Choose a preferred time.'); } if (step === 5 && !form.consent) e.push('Please agree to be contacted regarding this appointment request.'); setErrors(e); return e.length === 0;
  };
  const next = () => { if (validate()) setStep((x) => Math.min(5, x + 1)); };
  const submit = () => { if (!validate()) return; mutation.mutate({ data: form }, { onSuccess: () => setSuccess(true), onError: () => setErrors(['Something went wrong while sending your request. Please try again or call 438-872-0884.']) }); };
  if (success) return <Layout><main className="section"><div className="container-narrow"><div className="form-card form-success"><div className="success-mark"><Check size={28} /></div><div className="eyebrow">Booking request received</div><h2>Request received.</h2><p>Thanks for contacting Wizard’s Auto Detailing. Your appointment request has been submitted successfully. We’ll use the details provided to follow up and confirm availability.</p><div className="hero-cta" style={{ justifyContent: 'center' }}><Link href="/" className="button-gold" data-testid="link-book-success-home">Return home <ArrowRight size={14} /></Link><Link href="/services" className="button-ghost" data-testid="link-book-success-services">View services</Link></div><a href={`tel:${phone}`} className="placeholder-note" data-testid="link-book-success-phone">Need to speak with us? Call {phone}</a></div></div></main></Layout>;
  return <Layout><main><section className="page-hero"><div className="container-wide"><div className="eyebrow">Private appointment concierge</div><h1>Book your<br /><em>detail.</em></h1><p>Tell us about your vehicle and preferred appointment. We’ll use your information to coordinate your booking.</p></div></section><section className="section"><div className="container-wide form-layout"><aside className="form-aside"><div className="eyebrow">A booking request</div><h2>Good work<br />starts with<br /><em>good details.</em></h2><p>Your requested time is not confirmed until Wizard’s Auto Detailing contacts you. Location and scope are confirmed before the appointment.</p><div className="form-notice">Appointments are subject to location confirmation within the Wizard’s service area.</div></aside><div className="form-card"><div className="stepper">{bookingSteps.map((x, i) => <div className={`stepper-item ${i === step ? 'active' : ''} ${i < step ? 'done' : ''}`} key={x}>{String(i + 1).padStart(2, '0')} {x}</div>)}</div>{errors.length > 0 && <div className="form-alert" role="alert">{errors.map((x) => <div key={x}>{x}</div>)}</div>}<div className="form-step">
    {step === 0 && <><h3>Your contact details</h3><p className="form-step-intro">How should Wizard’s reach you about this request?</p><div className="field-grid"><Field label="Full name" name="fullName" value={form.fullName} onChange={(v) => set('fullName', v)} required /><Field label="Email address" name="email" type="email" value={form.email} onChange={(v) => set('email', v)} required /><Field label="Phone number" name="phone" type="tel" value={form.phone} onChange={(v) => set('phone', v)} required /><div className="field"><label htmlFor="preferredContactMethod">Preferred contact method</label><select id="preferredContactMethod" value={form.preferredContactMethod} onChange={(e) => set('preferredContactMethod', e.target.value)} data-testid="select-preferred-contact"><option value="phone">Phone</option><option value="text">Text</option><option value="email">Email</option></select></div></div></>}
    {step === 1 && <><h3>Your vehicle</h3><p className="form-step-intro">A few details help the team understand the vehicle before coordinating.</p><div className="field-grid"><Field label="Vehicle make" name="vehicleMake" value={form.vehicleMake} onChange={(v) => set('vehicleMake', v)} required /><Field label="Vehicle model" name="vehicleModel" value={form.vehicleModel} onChange={(v) => set('vehicleModel', v)} required /><Field label="Vehicle year" name="vehicleYear" type="number" value={form.vehicleYear ?? ''} onChange={(v) => set('vehicleYear', v ? Number(v) : null)} /><Field label="Vehicle color" name="vehicleColor" value={form.vehicleColor} onChange={(v) => set('vehicleColor', v || null)} /><div className="field"><label htmlFor="vehicleType">Vehicle type *</label><select id="vehicleType" value={form.vehicleType} onChange={(e) => set('vehicleType', e.target.value)} data-testid="select-vehicle-type">{['sedan', 'coupe', 'suv', 'truck', 'van', 'other'].map((x) => <option key={x} value={x}>{x[0].toUpperCase() + x.slice(1)}</option>)}</select></div><div className="field"><label htmlFor="vehicleCondition">Current condition</label><select id="vehicleCondition" value={form.vehicleCondition ?? 'unsure'} onChange={(e) => set('vehicleCondition', e.target.value)} data-testid="select-vehicle-condition"><option value="light">Light cleaning needed</option><option value="moderate">Moderate cleaning</option><option value="heavy">Heavy cleaning</option><option value="unsure">Not sure</option></select></div></div></>}
    {step === 2 && <><h3>Choose your service</h3><p className="form-step-intro">Select every service you would like to discuss. Not sure? Choose the last option.</p><div className="choice-grid">{[...services.map((s) => s.title), 'Not sure / Recommend a service'].map((x) => <label className={`choice ${form.services.includes(x) ? 'selected' : ''}`} key={x}><input type="checkbox" checked={form.services.includes(x)} onChange={() => set('services', form.services.includes(x) ? form.services.filter((y) => y !== x) : [...form.services, x])} data-testid={`checkbox-service-${x.toLowerCase().replaceAll(' ', '-')}`} /><span><b>{x}</b><span>{x === 'Not sure / Recommend a service' ? 'Tell us what you want improved.' : 'Request scope and availability.'}</span></span></label>)}</div><div className="field" style={{ marginTop: 18 }}><label htmlFor="serviceNotes">What would you like improved?</label><textarea id="serviceNotes" value={form.serviceNotes ?? ''} onChange={(e) => set('serviceNotes', e.target.value || null)} placeholder="Stains, pet hair, paint condition, specific areas of concern..." data-testid="textarea-service-notes" /></div></>}
    {step === 3 && <><h3>Where should we meet the vehicle?</h3><p className="form-step-intro">Home, workplace, or another suitable location.</p><div className="field-grid"><Field label="Service address" name="serviceAddress" value={form.serviceAddress} onChange={(v) => set('serviceAddress', v)} required /><Field label="City" name="city" value={form.city} onChange={(v) => set('city', v)} required /><Field label="Postal code" name="postalCode" value={form.postalCode} onChange={(v) => set('postalCode', v)} required /><div className="field"><label htmlFor="locationType">Location type</label><select id="locationType" value={form.locationType ?? ''} onChange={(e) => set('locationType', e.target.value || null)} data-testid="select-location-type"><option value="">Select one</option>{['House driveway', 'Apartment / condo', 'Workplace', 'Commercial location', 'Other'].map((x) => <option key={x}>{x}</option>)}</select></div><div className="field full"><label htmlFor="accessNotes">Parking and access details</label><textarea id="accessNotes" value={form.accessNotes ?? ''} onChange={(e) => set('accessNotes', e.target.value || null)} placeholder="Where will the vehicle be parked? Any access details?" data-testid="textarea-access-notes" /></div></div></>}
    {step === 4 && <><h3>Preferred appointment</h3><p className="form-step-intro">Choose a preferred time and an alternative if helpful.</p><div className="field-grid"><Field label="Preferred date" name="preferredDate" type="date" value={form.preferredDate} onChange={(v) => set('preferredDate', v)} required /><Field label="Preferred time" name="preferredTime" type="time" value={form.preferredTime} onChange={(v) => set('preferredTime', v)} required /><Field label="Alternative date" name="alternativeDate" type="date" value={form.alternativeDate} onChange={(v) => set('alternativeDate', v || null)} /><Field label="Alternative time" name="alternativeTime" type="time" value={form.alternativeTime} onChange={(v) => set('alternativeTime', v || null)} /></div><div className="form-notice">Your requested time is not confirmed until Wizard’s Auto Detailing contacts you.</div></>}
    {step === 5 && <><h3>One last look</h3><p className="form-step-intro">Anything else the team should know before reviewing your request?</p><div className="field-grid"><div className="field full"><label htmlFor="notes">Additional notes</label><textarea id="notes" value={form.notes ?? ''} onChange={(e) => set('notes', e.target.value || null)} placeholder="Stains, pet hair, paint condition, specific areas of concern, access instructions..." data-testid="textarea-booking-notes" /></div><label className="checkbox-row field full"><input type="checkbox" checked={form.consent} onChange={(e) => set('consent', e.target.checked)} data-testid="checkbox-booking-consent" /><span>I agree to be contacted regarding this appointment request.</span></label></div></>}
  </div><div className="form-nav">{step > 0 ? <button className="button-ghost" onClick={() => { setErrors([]); setStep((x) => x - 1); }} data-testid="button-book-back"><ArrowLeft size={14} /> Back</button> : <span />}{step < 5 ? <button className="button-gold" onClick={next} data-testid="button-book-next">Next step <ArrowRight size={14} /></button> : <button className="button-gold" onClick={submit} disabled={mutation.isPending} data-testid="button-book-submit">{mutation.isPending ? 'Sending request...' : 'Send booking request'} <ArrowRight size={14} /></button>}</div></div></div></section></main></Layout>;
}
export default BookPage;
