import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, ArrowDownRight, Instagram } from 'lucide-react';
import Layout from '@/components/Layout';
import { images, services, galleryItems, phone, instagram } from '@/lib/constants';
import { Phone } from 'lucide-react';

function Hero() {
  return <section className="hero">
    <div className="hero-media" style={{ backgroundImage: `url(${images.hero})` }} />
    <div className="container-wide hero-content"><div className="hero-kicker eyebrow">Montreal <span>•</span> Mobile auto detailing</div><h1>Precision in <em>every</em> detail.</h1><p className="hero-copy">Premium mobile interior, exterior, polishing and ceramic coating services — delivered to your location across Montreal and surrounding areas.</p><div className="hero-cta"><Link href="/book" className="button-gold" data-testid="link-hero-book">Book your detail <ArrowRight size={15} /></Link><Link href="/services" className="button-ghost" data-testid="link-hero-services">Explore services <ArrowDownRight size={15} /></Link></div><div className="credibility"><span>Mobile service</span><span>Professional detailing</span><span>Montreal & surrounding areas</span></div></div><div className="scroll-cue"><i /> Scroll to explore</div>
  </section>;
}

function GalleryPreview() {
  return <section className="section section-dark"><div className="container-wide"><div className="section-head"><div><div className="eyebrow">Recent details</div><h2>Follow the<br />finish.</h2></div><a href={instagram} target="_blank" rel="noreferrer" className="button-ghost" data-testid="link-home-instagram">Follow @wizards.detailing <Instagram size={14} /></a></div><div className="gallery-grid">{galleryItems.slice(0, 5).map((x) => <Link href="/gallery" className="gallery-tile" key={x.id} data-testid={`link-preview-gallery-${x.id}`}><img src={x.image} alt={`${x.category} detailing project placeholder`} /><div className="gallery-caption"><span>{x.title}</span><span>{x.category}</span></div></Link>)}</div><div style={{ marginTop: 25 }}><Link href="/gallery" className="button-ghost" data-testid="link-home-gallery">See all work <ArrowRight size={14} /></Link></div></div></section>;
}

function Home() {
  const [compare, setCompare] = useState(48);
  return <Layout><main>
    <Hero />
    <section className="section section-soft"><div className="container-wide editorial"><div><div className="eyebrow">The Wizard’s standard</div><h2>More than clean.<br /><em>Meticulously finished.</em></h2></div><div className="editorial-copy"><p className="body-copy">Wizard’s Auto Detailing provides professional mobile detailing with careful attention to every surface, finish and final reflection. From everyday vehicles to premium cars, every detail is handled with precision.</p><Link href="/about" className="button-ghost" data-testid="link-standard-about">Our approach <ArrowRight size={14} /></Link></div></div><div className="container-wide values">{[['Precision', 'Every surface considered.'], ['Convenience', 'Professional care, wherever you are.'], ['Finish', 'A result you can see and feel.']].map(([x, y]) => <div className="value" key={x}><b>{x}</b><span>{y}</span></div>)}</div></section>
    <section className="section"><div className="container-wide"><div className="section-head"><div><div className="eyebrow">Services</div><h2>Built around<br />your vehicle.</h2></div><p>Thoughtful service options for the cabin, the bodywork, and the finish that brings it all together.</p></div><div className="services-grid">{services.map((s) => <Link href={`/services/${s.slug}`} className="service-card" key={s.slug} data-testid={`link-service-card-${s.slug}`}><div className="service-card-media" style={{ backgroundImage: `url(${s.image})` }} /><div className="service-card-content"><div className="service-number">{s.number} / 04</div><h3>{s.title}</h3><p>{s.description}</p><span className="card-link">View service <ArrowRight size={14} /></span></div></Link>)}</div></div></section>
    <section className="section section-dark"><div className="container-wide"><div className="section-head"><div><div className="eyebrow">Finish, in focus</div><h2>See the<br />difference.</h2></div><p>Use the comparison control to explore the finish. Real Wizard’s project photos can be placed here when supplied.</p></div><div className="comparison" style={{ ['--compare' as string]: `${compare}%` }}><div className="comparison-img comparison-before" style={{ backgroundImage: `url(${images.exterior})` }} /><div className="comparison-img comparison-after" style={{ backgroundImage: `url(${images.exterior})` }} /><span className="comparison-label before">Before</span><span className="comparison-label after">After</span><div className="comparison-handle" /><input className="comparison-range" type="range" min="5" max="95" value={compare} onChange={(e) => setCompare(Number(e.target.value))} aria-label="Before and after comparison" data-testid="input-comparison" /></div><span className="placeholder-note">Replace with verified Wizard’s before / after project imagery</span></div></section>
    <section className="section"><div className="container-wide split-visual"><div className="visual-frame" style={{ backgroundImage: `url(${images.work})` }} /><div><div className="eyebrow">Mobile by design</div><h2>Premium detailing.<br /><em>Wherever you are.</em></h2><p className="body-copy">Home, workplace or another suitable location — Wizard’s brings professional detailing to you across Montreal and surrounding areas.</p><div className="process">{[['01', 'Choose your service', 'Select the detailing service that suits your vehicle.'], ['02', 'Choose your location', 'Enter where the vehicle will be available.'], ['03', 'Book your time', 'Submit your preferred appointment date and time.']].map(([n, t, d]) => <div className="process-step" key={n}><div className="process-index">{n}</div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><Link href="/book" className="button-gold" data-testid="link-mobile-book">Book mobile detailing <ArrowRight size={14} /></Link></div></div></section>
    <section className="ceramic-feature"><div className="container-wide ceramic-content"><div className="eyebrow">Ceramic coating</div><h2>Protection meets reflection.</h2><p>Ceramic coating adds a protective layer over the vehicle’s finish while enhancing gloss, water behavior and ease of maintenance. Wizard’s focuses on careful preparation and application for a clean final result.</p><Link href="/services/ceramic-coating" className="button-ghost" data-testid="link-ceramic-home">Learn about ceramic coating <ArrowRight size={14} /></Link></div><div className="droplets" /></section>
    <GalleryPreview />
    <section className="section section-soft"><div className="container-wide quote-block"><div><div className="eyebrow">A note from the studio</div><div className="quote-mark">“</div></div><div><div className="quote-text">The customer review space is ready for the words of a verified Wizard’s client.</div><span className="placeholder-note">Insert verified customer review, name, vehicle and source</span></div></div></section>
    <section className="section"><div className="container-wide about-grid"><div><div className="eyebrow">Our story</div><h2>Built on the details others miss.</h2><p className="body-copy">Wizard’s Auto Detailing is a mobile detailing team serving Montreal and surrounding areas. The work is simple in principle: care for the vehicle, respect the location, and leave the finish feeling considered.</p><Link href="/about" className="button-ghost" data-testid="link-home-about">Discover the approach <ArrowRight size={14} /></Link></div><div className="about-image" style={{ backgroundImage: `url(${images.detail})` }} /></div></section>
    <section className="cta-band"><div className="container-wide"><div className="eyebrow">Your vehicle, next</div><h2>Ready for a better finish?</h2><p>Tell us about your vehicle, choose the service you need, and request your preferred appointment time.</p><div className="cta-actions"><Link href="/book" className="button-gold" data-testid="link-home-cta-book">Book an appointment <ArrowRight size={15} /></Link><a href={`tel:${phone}`} className="button-ghost" data-testid="link-home-cta-phone">Call {phone} <Phone size={14} /></a></div></div></section>
  </main></Layout>;
}
export default Home;
