import { Link, useParams } from 'wouter';
import { ArrowRight, ChevronDown } from 'lucide-react';
import Layout from '@/components/Layout';
import { services } from '@/lib/constants';

function ServiceDetail() {
  const { slug } = useParams<{ slug: string }>();
  const service = services.find((x) => x.slug === slug) ?? services[0];
  const steps = service.slug === 'interior-detailing' ? ['Vehicle inspection', 'Vacuum and surface reset', 'Cabin detail', 'Final walkthrough'] : service.slug === 'exterior-detailing' ? ['Vehicle inspection', 'Wash and wheel care', 'Surface decontamination', 'Exterior finish'] : service.slug === 'polishing' ? ['Paint inspection', 'Surface preparation', 'Machine polishing', 'Final inspection'] : ['Vehicle inspection', 'Surface preparation', 'Decontamination', 'Application'];
  return <Layout><main><section className="detail-hero" style={{ backgroundImage: `url(${service.image})` }}><div className="container-wide detail-hero-content"><div className="eyebrow">{service.number} / Wizard’s service</div><h1>{service.title}</h1><p className="hero-copy">{service.description}</p></div></section><section className="section"><div className="container-wide detail-overview"><div><div className="eyebrow">The service</div><h2>Care begins<br />with the surface.</h2></div><div><p className="body-copy">{service.description} Wizard’s approaches each vehicle with a clear inspection, careful preparation, and a final look at the details that shape the result.</p><p className="body-copy">This service is a request for coordination. Scope, suitability, and any client-specific inclusions are discussed before the appointment is confirmed.</p><Link href="/book" className="button-gold" data-testid={`link-detail-book-${service.slug}`}>Request this service <ArrowRight size={14} /></Link></div></div></section><section className="section section-dark"><div className="container-wide"><div className="eyebrow">What the process looks like</div><h2 style={{ margin: '12px 0 45px', fontFamily: 'var(--app-font-serif)', fontWeight: 400, fontSize: 'clamp(42px, 6vw, 74px)', lineHeight: .9 }}>Measured. Clean. <em>Finished.</em></h2><div className="detail-process">{steps.map((x, i) => <div className="detail-step" key={x}><b>0{i + 1}</b><h3>{x}</h3><p>Exact stages are confirmed around the vehicle and requested service.</p></div>)}</div></div></section><section className="section"><div className="container-wide faq"><h2>Questions worth<br /><em>asking.</em></h2><div className="faq-list"><details className="faq-item"><summary>Is this service available at my location? <ChevronDown size={16} /></summary><p>Wizard’s serves Montreal and surrounding areas. Appointments remain subject to location confirmation within the service area.</p></details><details className="faq-item"><summary>How do I know which service is right? <ChevronDown size={16} /></summary><p>Send a booking request with your vehicle details and what you want improved. The team can use that context to coordinate the right scope.</p></details><details className="faq-item"><summary>Are prices shown online? <ChevronDown size={16} /></summary><p>Pricing is not shown until service scope and vehicle details are confirmed by the client.</p></details></div></div></section><section className="cta-band"><div className="container-wide"><div className="eyebrow">{service.title}</div><h2>Make space for the finish.</h2><Link href="/book" className="button-gold" data-testid="link-detail-final-book">Request this service <ArrowRight size={14} /></Link></div></section></main></Layout>;
}
export default ServiceDetail;
